services:
  sub2api:
    image: weishaw/sub2api@sha256:5433a314b1dacce7882d0739a6ec24bdec1419a93fba5a34bdecad950137cbb5
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "5"

  postgres:
    image: postgres@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "5"

  redis:
    image: redis@sha256:9d317178eceac8454a2284a9e6df2466b93c745529947f0cd42a0fa9609d7005
    command:
      - sh
      - -ec
      - |
        exec redis-server \
          --save 60 1 \
          --appendonly yes \
          --appendfsync everysec \
          --requirepass "$${REDISCLI_AUTH}"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
